### PR TITLE
add swift uvot bandpasses

### PR DESCRIPTION
**Pull request by dannygoldstein**

### CODE REVIEW

**Comment by dannygoldstein** [comment]
ready for review

**Comment by kbarbary** [comment]
Just checking: are you planning to add these as built-ins in sncosmo?

**Comment by dannygoldstein** [comment]
Wanted to wait for closure on https://github.com/sncosmo/sncosmo/issues/268 before proceeding

**Comment by kbarbary** [comment]
Just curious: are these copies from the SVO?

**Comment by dannygoldstein** [comment]
Yes

**Pull request merged**
