### PR TITLE
Replaced remote download wfc3 IR and UVIS filters

### PR DESCRIPTION
**Pull request by jpierel14**
This is to fix issue sncosmo/sncosmo#246, since the wfc3 throughput tables moved. I've added wfc3-ir and wfc3-uvis folders with all the medium, wide, and long pass filters along with anything that was already in sncosmo. A couple of things though:

1.  Can't find the ACS WFC filters anywhere, used to be at http://www.stsci.edu/hst/acs/analysis/throughputs, so those still won't work

2. I chose to take an average of chips 1 and 2 for UVIS throughputs, we could replace that with one or the other if needed.

### CODE REVIEW

**Comment by kbarbary** [comment]
Thank you for moving this fix forward! :clap:

One enhancement: If we could keep the same file names as before, we wouldn't have to change sncosmo code itself and the fix will start working right away for all versions of sncosmo: users will not have to upgrade to get the fix (or wait until a new version is released).

I have a downloaded copy of the ACS WFC filters locally that I can push up in a separate PR.

**Comment by jpierel14** [comment]
Sure I can change the file names, to (for example ) f140w.IR.tab? I did add some bands that weren't there before, so I'll still submit a pull request for sncosmo but it won't be necessary to have this fix work.

**Comment by jpierel14** [comment]
That should be good with 190d651, unless I misunderstood. Let me know. I left the sncosmo pull request (with updated filenames) as well because of the added filters, but that one is not urgent.

**Comment by kbarbary** [comment]
Looks great.

**Pull request merged**
