### PR TITLE
New CCSN and PopIII models

### PR DESCRIPTION
**Pull request by srodney**
This is a big commit, with ~200 MB of new SED files for the complete SNANA CC SN template library, plus a handful of PopIII models from Dan Whalen et al.  
Once accepted, I'll post another pull request in the main sncosmo branch, with an update to sources.py for loading these models.

### CODE REVIEW

**Comment by kbarbary** [comment]
I was initially putting all the models in a flat directory structure, but I think it might be time to start organizing them into directories as you've done with the new files. I have a preference for organizing by author, unless the name of the model is really well defined, such as with SALT2. I'd probably organize the existing files like:

```
hsiao/Hsiao_SED.fits
      Hsiao_SED_V2.fits
      Hsiao_SED_V3.fits
sako/S11_SDSS-000018.SED
     S11_SDSS-001472.SED
     S11_SDSS-002000.SED
     ...
salt2/salt2_extended.tar.gz
```

I like the "by-author" organization because it makes the provenance of the model data clear, and because models from the same author tend to have similar properties (in terms of both the data format and the black magic by which they were created).

The Pop III models could go under `whelan/`. Are the SNANA CC SN models in a publication anywhere, or is the creator clear? If so, I'd use the author. Alternatively, we could just put them under `snana/` if that's the only place they're published.

**Comment by kbarbary** [comment]
Or we could just dump everything into a flat directory structure and say the hell with it. :)

**Comment by srodney** [comment]
I like the sub-directories by author.  Updated in 6894277.   
Note that I put salt2_extended in the "snana" subdir, alongside the 42 core-collapse models.  The CC models are based on spectra and light curves that are published separately in like a dozen different papers, but they only exist as complete spectrophotometric time series in the SNANA library, AFAIK. 

I have an accompanying commit in my fork of sncosmo/sncosmo with sources.py updated. Is there a way to link that into this sncosmo.github.io pull request?  

As an aside, I think the salt2-extended model is just the hacked up version of SALT2 that I added to SNANA a few years ago.   It was a very crude extrapolation that I did so that SNANA could handle the very blue and red HST filters from CANDELS and CLASH for quick+dirty SN classification work.  It was not ever intended for cosmology, and I know that it misbehaves badly at extreme parameter values, redshifts and wavelengths.   Perhaps we should add some red blinking caveats to the docs somewhere.

**Comment by kbarbary** [comment]
One problem that I didn't mention: we have to leave copies of the already-existing models where they are, for the benefit of anyone running v0.4.2 code (since the URLs are fixed in that code). We can remove them at a later date, once we think nearly everyone has upgraded to a more recent version.

I have a potential solution for the redirect thing: We keep a single JSON-format file at `sncosmo.github.io/data/urls.json` (or whatever name). It would contain the true URL for any data or model. We then refactor the code in sncosmo/_builtins to always download this file and look up the true URL for any data or model. That URL could be on github or on someone else's server. I can work on this after you add your changes to sources.py. Once we do this, we only need to worry about keeping that single (small) file at a fixed URL: we can reorganize all the data at will and just change the URL in that file.

I think you're right that it's more proper to put salt2-extended in the `snana` directory if we're doing it by author (though its unfortunate to have it split off from the other salt2 templates). BTW I'm surprised at how good the `salt2-extended` template looks outside the normal support wavelength range, given that it's a hack! Also, it has been really useful for photometric typing, so big thanks for that.

PS: I've found some pretty bad problems with some of the SNANA CC models, hence sncosmo/sncosmo#56 for machinery to make better templates from the original data.

(You may be able to link to commits in other repos in the same way that I linked to the PR above.)

**Comment by kbarbary** [comment]
For now let's just move the hsiao, sako and salt2_extended models back up to the top level. The new models can stay in their subdirectories (snana, whelan). As soon as you do that I think we can merge this and continue progressing.

**Comment by srodney** [comment]
OK.  That's fine with me. 

To clarify my question on linking the commits:  I was wondering not about hyperlinks in the comments, but about linking the commits themselves.  Every update to the locations of the data in sncosmo.github.io should have a corresponding update in sncosmo/sncosmo/_builtin/sources.py, but those are in two separate repositories, and I'm not sure it if it is possible to create a single pull request that would contain both of those commits.

**Comment by kbarbary** [comment]
I see now. I don't know of any way to do that. I guess it's just not a typical thing to do. git can do dependencies between repositories, but its through git submodules.

**Pull request merged**
