### PR TITLE
add ztf bandpasses

### PR DESCRIPTION
**Pull request by dannygoldstein**

### CODE REVIEW

**Comment by dannygoldstein** [comment]
@ufeindt are these still the best ztf bandpasses to use (using the versions from dannygoldstein/sncosmo@29b488d)

**Comment by dannygoldstein** [comment]
@ufeindt  the meta in dannygoldstein/sncosmo@29b488d say no atmospheric corrections, would be really good to have a version with atmospheric corrections  (at least at some average level). do these exist?

**Comment by kbarbary** [comment]
:+1: I'll wait for a decision on the above question before merging...

**Comment by ufeindt** [comment]
Yes, they are currently still the best bandpasses I have. Haven't seen an atmospheric correction yet. I know we have it planned for the future, though.

**Comment by dannygoldstein** [comment]
In that case I think this is ready to be merged on my end

**Pull request merged**
